#!/bin/bash
# Copyright 2025-present, Synopsys, Inc.
# All rights reserved.
#
# This source code is licensed under the GPL-3.0 license found in
# the LICENSE file in the root directory of this source tree.

riscv64-unknown-elf-gcc -march=rv64gc -mabi=lp64 "$@"

