#!/bin/bash
# Copyright 2025-present, Synopsys, Inc.
# All rights reserved.
#
# This source code is licensed under the GPL-3.0 license found in
# the LICENSE file in the root directory of this source tree.

riscv32-unknown-elf-gcc -march=rv32gc -mabi=ilp32 -DCONFIG_FPU=0 "$@"

